# Generated by Django 4.0.2 on 2022-02-10 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_alter_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='trackable_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9b28abb-f21c-4323-a7fd-f5048fd23439'), primary_key=True, serialize=False),
        ),
    ]
