# Generated by Django 4.0.2 on 2022-02-10 05:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0003_link_trackable_link_alter_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='bucket.link'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48c2b015-2ea4-4f21-96f5-82f8d7c2d34e'), primary_key=True, serialize=False),
        ),
    ]
