# Generated by Django 4.0.2 on 2022-04-03 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0006_alter_vote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22c6071c-874e-480e-9241-32bd89373065'), primary_key=True, serialize=False),
        ),
    ]
