# Generated by Django 4.0.2 on 2022-04-03 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0009_alter_vote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.UUIDField(default=uuid.UUID('867d86d9-2acd-470a-be27-440d1b377b83'), primary_key=True, serialize=False),
        ),
    ]
